### PR TITLE
Adding Command Line support

### LINKED ISSUE #10: Allow running on the CLI?
This would be great:

```shell
npm i -g is-windows

is-windows && echo "I'm on Windows!"
```

### PR DESCRIPTION
**Pull request by computamike**
To Fix #10 - Have Added CLI support.  If you issue the command ```is-windows``` the CLI returns true / false.

Developed this on a mac  - tested as best I can - but can someone please confirm on windows?

### CODE REVIEW

**Comment by computamike** [comment]
Hi @jonschlinkert  - have you had time to take a look at this PR?  thanks

**Comment by i3anaan** [comment]
So a package that is used over 2 million times is not even responding to a PR after almost a full year has passed? To me, that shows the stupidity of this package.

**Comment by jonschlinkert** [comment]
@i3anaan I usually don't respond to trolls, but I will make an exception. 

Let's zoom out and look at this from a different angle. How about a simple question:

**Why would someone create such a library such as this?**

Well, thank you for asking. I'm glad you didn't make any assumptions. The answer is simple: some of our users created bug reports to notify us that their OS wasn't correctly identified. Namely, when using `msys` and `cygwin`. Given that:

- I don't use either
- I only use Windows for testing
- I have created dozens of CLI libraries and we have millions of users, I didn't want to repeat this [one line of code](https://github.com/jonschlinkert/is-windows/blob/master/index.js#L25) manually, over and over again. 

Now that we got that out of the way. 

Closing the PR and blocking @computamike since this is obviously an attempt at trolling. Unfortunately, I'm also blocking @i3anaan for the hostility.

**Comment by jonschlinkert** [comment]
@computamike if I misunderstood, and this was a serious PR, then I apologize, and please contact me at my email address on my profile and I'll get you unblocked.

**Pull request closed without merging**
